version: '2'

services:
  mongodb2:
    image: mongo
    ports:
      - 27017:27017
    container_name: "mongodb2"
  mysql:
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: devidea
    container_name: mysql
    command: # 명령어 실행
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

  devidea:
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_ADDRESS: mysql
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 1234
    links:
      - mongodb2
      - mysql
