server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true

jwt:
  header: Authorization
  secret: devidea
  token-validity-in-seconds: 86400
sns:
  google:
    url: https://accounts.google.com/o/oauth2/v2/auth
    client:
      id: 9719839326-fnc7hcgbq8nit8qp6s3ip7vrfn01gche.apps.googleusercontent.com
      secret: k64ajtdh7iPfaEkW_TjbwiGm
    callback:
      url: http://localhost:8080/login/oauth/google/callback